version: '3.8'

services:
  agentern_api:
    build: .
    container_name: agentern
    ports:
      - "17111:8000"
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_URL=http://172.17.0.1:11434/api/generate
      - PYTHONPATH=/app
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_DB_PATH=${CHROMADB_PATH:-}"
    networks:
      - agentern_net

networks:
  agentern_net:
    driver: bridge